import React from "react";
import "./index.css";
import Provider from "./provider";

const metadata = {
  title: "Create React App",
  description: "Generated by create react app",
};

const fontConfig = {
  fontFamily: "Inter, sans-serif",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren<{}>) {
  return (
    <div lang="en" suppressHydrationWarning style={fontConfig}>
        <Provider>{children}</Provider>
    </div>
  );
}
